### ISSUE TITLE
journal - make timestamp generic

### ISSUE THREAD

**Issue by tisonkun** [engula/engula#100]
What do you mean by "make it generic"? Does it mean:

```rust
pub struct Event<TS> {
    pub ts: TS,
    pub data: Vec<u8>,
}
```

or `Timestamp<T>`? Is there similar stuff in other projects?

cc @huachaohuang

_Originally posted by @tisonkun in https://github.com/engula/engula/pull/82#r748146358_

The `Event<TS>` one, but should be more complicated than that. The rationale is to let users customize the type of the timestamp. Depending on how users implement their databases, the usage of timestamp can be very different. For example, it can be a simple increasing counter, a logical lock, or a hybrid logical lock, which may need different representations.

_Originally posted by @huachaohuang in https://github.com/engula/engula/pull/82#discussion_r748150920_

**Comment by tisonkun** [comment]
I made a try in [this branch](https://github.com/tisonkun/engula/tree/timestamp) but believe there must be some best practices I miss - code should never be written as this XD.

Even I make Timestamp a simple `Ord` bounded trait it brings `<Timestamp: Ord + Display + Send + Clone + Copy>` everywhere. And I have to make two hacks.

1. Introduce `'static +` to workaround lifetime gap in async context (which IMO is a unreasonable restriction for this concept).
2. Change `.unwarp_or(0)` to `.unwrap` due to `Ord` itself doesn't provide a reasonable "default" in "last_ts" context. We may introduce a new trait but I don't have a good background on it.

**Comment by tisonkun** [comment]
Well I reduce the repetition a bit by factoring out:

```rust
pub trait Timestamp: Ord + Display + Send + Copy {}
impl<T> Timestamp for T where T: Ord + Display + Send + Copy {}
```

but the two questions above remain.

**Comment by tisonkun** [comment]
I guess `unwrap_or(0)` means `unwrap_or_default` and add a trait bound `Default` to overcome the first question. Here is the draft pull request https://github.com/engula/engula/pull/103 .

However, I don't still work well with lifetime, and am unsure whether `Timestamp` is so basic and essential that we almost affect every abstraction in `journal` - is it worth?

**Comment by Xuanwo** [comment]
Sorry for jumping into this discussion without more research.

As we will store the journal remotely, we need to consider how to ser/de the `Timestamp`. Compared to using a trait, maybe we can use a struct here, and let users decide how to convert their `Timestamp` into ours?

**Comment by huachaohuang** [comment]
> As we will store the journal remotely, we need to consider how to ser/de the `Timestamp`. Compared to using a trait, maybe we can use a struct here, and let users decide how to convert their `Timestamp` into ours?

Can you elaborate a little bit? I don't see how a struct solves the problem here.

**Comment by tisonkun** [comment]
@Xuanwo we introduce `Timestamp` to avoid this conversion.

Suppose we force `Timestamp` as `u64` and let users convert their own types to a `u64`. It sounds reasonable for several cases. But a DateTime may fail to convert to `u64` with UNIX epoch conversion if it exceeds. Also, a hybrid logic clock may hard to be convert into `u64`. That's why we introduce `Timestamp` abstraction - release users from considering all of this stuff.

**Comment by Xuanwo** [comment]
Well, I got it. Thanks for explaining to me!
