### ISSUE TITLE
 ci - cargo clippy should be run with --tests

### ISSUE THREAD

**Issue by PsiACE** [engula/engula#105]
Otherwise tests aren't covered.

**Comment by tisonkun** [comment]
@PsiACE I notice that maybe we should keep `CONTRIBUTING.md` up-to-date also. Would you like to take a look or create an issue first?

**Comment by tisonkun** [comment]
We take about how to run tests and linters in `CONTRIBUTING.md ` but out-of-sync in this issue and #101 :P

**Comment by PsiACE** [comment]
> @PsiACE I notice that maybe we should keep `CONTRIBUTING.md` up-to-date also. Would you like to take a look or create an issue first?

I will update it. Shall we consider adding a makefile to simplify the commands?

**Comment by tisonkun** [comment]
@PsiACE I tend not to do so - it's a bit over-engineering. Cargo is designed to be self-service, and even projects like tokio don't require a Makefile. I prefer to collaborate with the Rust community than maintain two build tools.

**Comment by PsiACE** [comment]
> @PsiACE I tend not to do so - it's a bit over-engineering. Cargo is designed to be self-service, and even projects like tokio don't require a Makefile. I prefer to collaborate with the Rust community than maintain two build tools.

Well, if it is necessary, we can add some custom cmd to .cargo/config.toml. Of course, it's too early.
