### ISSUE TITLE
Investigate how to test with s3

### ISSUE THREAD

**Issue by zojw** [engula/engula#109]
ref https://github.com/engula/engula/pull/99#discussion_r748133615

need some method to automatic test with AWS service like s3 in CI without leaking access&secret key, IMHO, maybe we can do it in two directions:

- unit test: mock AWS SDK, there are exists an [issue](https://github.com/awslabs/aws-sdk-rust/issues/199#issuecomment-904558631 ) indicates SDK support TestConnection to mock/record request-response and we take some [tries](https://github.com/engula/engula/pull/99/files#diff-f6197926e0b89ec759315b9bd0efe5800b0eb88a71ece6d2a60746dd07b98af7R60), but it seems we need more encapsulation works to make it easy for use.
- integration-test: deploy a temp S3-like service(for example https://min.io/) in CI pipeline and make test case using temp S3-like service.

Welcome to give more advice or contribution code 😄

**Comment by PsiACE** [comment]
>     * unit test: mock AWS SDK, there are exists an [issue](https://github.com/awslabs/aws-sdk-rust/issues/199#issuecomment-904558631) indicates SDK support TestConnection to mock/record request-response and we take some [tries](https://github.com/engula/engula/pull/99/files#diff-f6197926e0b89ec759315b9bd0efe5800b0eb88a71ece6d2a60746dd07b98af7R60), but it seems we need more encapsulation works to make it easy for use.

Maybe have a look at rusoto_s3 ? I'm not sure, maybe a account is needed to test.

>     * integration-test: deploy a temp S3-like service(for example https://min.io/) in CI pipeline and make test case using temp S3-like service.

It's totally feasible

**Comment by PatrickNicholas** [comment]
> * integration-test: deploy a temp S3-like service(for example [min.io](https://min.io/)) in CI pipeline and make test case using temp S3-like service.

+1

**Comment by tisonkun** [comment]
@zojw I'm trying minio and find that it fails to respond to `put_public_access_block` request:

```
Error: expected element type <CreateBucketConfiguration> but have <PublicAccessBlockConfiguration> (xml.UnmarshalError)
       5: cmd/handler-utils.go:55:cmd.parseLocationConstraint()
       4: cmd/auth-handler.go:330:cmd.checkRequestAuthTypeCredential()
       3: cmd/auth-handler.go:282:cmd.checkRequestAuthType()
       2: cmd/bucket-handlers.go:695:cmd.objectAPIHandlers.PutBucketHandler()
       1: net/http/server.go:2046:http.HandlerFunc.ServeHTTP()
```

https://github.com/minio/minio/issues/13714

**Comment by tisonkun** [comment]
I pushed a branch running IT with MinIO [here](https://github.com/tisonkun/engula/tree/s3-itcase). You can take a look but I think given MinIO is not fully s3 compatible, we should try to find something better for our requirements, e.g., [localstack](https://github.com/localstack/localstack).

**Comment by zojw** [comment]
> I pushed a branch running IT with MinIO [here](https://github.com/tisonkun/engula/tree/s3-itcase). You can take a look but I think given MinIO is not fully s3 compatible, we should try to find something better for our requirements.

thanks, @tisonkun MinIO is probably the most popular S3 available replacement, it's a surprise that it doesn't support set PublicAccessBlock Policy - -, but it may indicate that the function [isn't very useful](https://github.com/simonw/s3-credentials/issues/20#issuecomment-965967392)

After some search, maybe we can remove set PublicAccessBlock logic and set ACL in CreateBucket to protect bucket data

```
@@ -68,25 +65,12 @@ impl Storage<S3Object, S3Bucket> for S3Storage {
             .build();
         self.client
             .create_bucket()
+            .acl(BucketCannedAcl::Private)
             .bucket(name.to_owned())
             .create_bucket_configuration(config)
             .send()
             .await?;

-        self.client
-            .put_public_access_block()
-            .bucket(name.to_owned())
-            .public_access_block_configuration(
-                PublicAccessBlockConfiguration::builder()
-                    .restrict_public_buckets(true)
-                    .block_public_policy(true)
-                    .ignore_public_acls(true)
-                    .block_public_acls(true)
-                    .build(),
-            )
-            .send()
-            .await?;
-
```
```

**Comment by tisonkun** [comment]
@zojw thanks! Let me try to create a pull request for this test.

But actually, as we go much deeper into s3 support, we have to introduce a sponsored s3 environment for testing - the most s3 "compatible" service is s3 itself.
