### ISSUE TITLE
Setup workflow to check unnecessary dependencies

### ISSUE THREAD

**Issue by zojw** [engula/engula#110]
ref https://github.com/engula/engula/pull/99#discussion_r750047678

maybe we can add https://github.com/est31/cargo-udeps to git workflow, just like `cargo audit`

**Comment by DCjanus** [comment]
What should be done when there are some unnecessary dependencies were reported by `cargo-udeps`, break pipeline and reject the pull request, or just a warning?

**Comment by huachaohuang** [comment]
I think we treat this similar to a style error and reject the PR. Maybe we can see how other projects handle it.

**Comment by tisonkun** [comment]
I submit a PR for addressing this issue. But cargo-udeps itself gives false negative in some cases. See also https://github.com/est31/cargo-udeps/issues/108.

**Comment by huachaohuang** [comment]
> I submit a PR for addressing this issue. But cargo-udeps itself gives false negative in some cases. See also [est31/cargo-udeps#108](https://github.com/est31/cargo-udeps/issues/108).

Hmm, maybe it is a [known bug](https://github.com/est31/cargo-udeps#known-bugs).

**Comment by tisonkun** [comment]
https://github.com/est31/cargo-udeps/issues/68#issuecomment-980354660 a potential improvement based on `actions/cache`.

```yaml
- uses: actions/cache@v2
  with:
    path: |
      ~/.cargo/bin/
      ~/.cargo/registry/index/
      ~/.cargo/registry/cache/
      ~/.cargo/git/db/
      target/
    key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
```
