### ISSUE TITLE
Security audit found one vulnerability

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#111]
https://github.com/engula/engula/runs/4233986277?check_suite_focus=true

**Comment by tisonkun** [comment]
This seems like we set all crate versions as `0.1.0` which conflicts with the released 0.1.0. I volunteer to prepare a fix.

**Comment by huachaohuang** [comment]
Hmm, maybe @zojw has fixed this [here](https://github.com/engula/engula/pull/99/commits/f0ee69ddf687d798a5a23aada9dc37e36e54ca81).

**Comment by tisonkun** [comment]
@huachaohuang you're right on the vulnerability. Then the proposal I made will address the warning and prepare for the 0.2.0 release.

Also, we may not create issue for a unmerged pull request.
