### ISSUE TITLE
A remote journal implementation

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#117]
We can wrap a gRPC Journal similar to [the gRPC Storage](https://github.com/engula/engula/tree/main/src/storage/src/grpc). I think it is not very hard, so maybe someone can give it a try :)

**Comment by tisonkun** [comment]
That sounds interesting. I'd like to give it a try this week. @huachaohuang could you assign it to me?

**Comment by tisonkun** [comment]
The first problem I met is that we use a generic `Timestap` type parameter. But I don't have an idea how to pass it through protobuf. I guess protobuf isn't aware of generic and I possibly need to do some unchecked casting.

**Comment by huachaohuang** [comment]
> The first problem I met is that we use a generic `Timestap` type parameter. But I don't have an idea how to pass it through protobuf. I guess protobuf isn't aware of generic and I possibly need to do some serde or unchecked casting.

I think we need to add some required methods in the trait sooner or later. For example, we can add methods to encode/decode `Timestamp` so that we can pass it as bytes.

> I may start with a `u64` only implementation first.

This also makes sense to me as a start.
