### ISSUE TITLE
Find tool and add Github Action to check toml files

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#120]
We have two toml files style now. For example, [this](https://github.com/engula/engula/blob/main/src/platform/aws/Cargo.toml) uses the style:

```
tokio = {version = "1.13", features = ["full"]}
```

But [this](https://github.com/engula/engula/blob/main/src/storage/Cargo.toml) use the style:

```
tokio = { version = "1.13", features = ["full"] }
```

Note the whitespace between `{}`. It would be nice to keep toml files consistent for all contributors.

**Comment by PatrickNicholas** [comment]
I find a tool 'taplo' which provide a cli to check toml file's format, but it seems that couldn't check the style, eg `{xxx}` vs `{ xxx }`.

You can install it by cargo:
```
cargo install taplo-cli
```

**Comment by huachaohuang** [comment]
Hmm, maybe it is just my obsession with consistency 🤔

**Comment by DCjanus** [comment]
> but it seems that couldn't check the style

I've created [an issue](https://github.com/tamasfe/taplo/issues/191) to request this feature, and provide a [very basic implementation](https://github.com/tamasfe/taplo/pull/192), hope this work.
