### ISSUE TITLE
Merge Bucket into Storage

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#127]
We have three traits for the storage component now: `Storage`, `Bucket`, `Object`. This brings two problems:

- The trait bound is a bit complicated, like `Storage<Object, Bucket>`
- There are some corner cases dealing with individual buckets, for example, https://github.com/engula/engula/pull/86#discussion_r750893023

A simpler solution is to merge Bucket into Storage, so Storage will provide the following interfaces:

- list buckets
- create bucket
- delete bucket
- list objects in a bucket
- upload an object to a bucket
- delete an object from a bucket

We can still keep `Object` and `ObjectUploader` as usually. Note that only `Object` is performance-critical here, as users may read from an object frequently. Other storage operations don't need to care about performance very much.

**Comment by zojw** [comment]
Hi, I'd like to take this :)
