### ISSUE TITLE
A file journal implementation

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#128]
We have a `mem` and `grpc` implementation now. But most applications will need persistent journal storage. A sophisticated implementation is not easy, we can start with a naive implementation for now. Check [RocksDB LogWriter](https://github.com/facebook/rocksdb/blob/main/db/log_writer.h) for an example.

**Comment by ztelur** [comment]
Hi, I am interested in this job, plz assign it to me

**Comment by huachaohuang** [comment]
@ztelur Thanks for your interest! Since you are new here, I need to make sure that you have enough context about the job before assigning it to you. So would you like to describe your plan for this job first? Do you need more information?

**Comment by ztelur** [comment]
ok. I am a rookie in storage system. I will make a plan and an approximate timetable

**Comment by huachaohuang** [comment]
@ztelur A simple description about what and how you are going to implement should be good enough. I just need to make sure that we are on the same page.

**Comment by tisonkun** [comment]
@ztelur the abstraction of Journal is defined by @huachaohuang already.

https://github.com/engula/engula/blob/00abae94aa27a520ef1dfd9cdc60b716822f8c13/src/journal/src/journal.rs#L19-L28

...and [a storage implementation based on local files](https://github.com/engula/engula/tree/main/src/storage/src/file) can be referred also.

> I am a rookie in storage system.

I don't think it makes any sense to move this issue forward. If you need more information, spell it out.

**Comment by DCjanus** [comment]
Should we limit size of each event, since this may affect the underlying design.

**Comment by huachaohuang** [comment]
> Before anyone start this task, should we limit size of each event? since this may affect the underlying design and leak from API design.
> 
> For example, for some WAL design, log would not be able to cross fix sized chunk or file, which required most log have a suitable size.

I think the semantic of Journal doesn't specify any size limit. So it is really up to the implementation. But I think a reasonable size range should be a few bytes to tens of megabytes. Of course, someone may choose to implement a Journal that only accepts fixed size events but performs so well that some user just accepts the size constraint.

**Comment by huachaohuang** [comment]
If we assume that there will not be too many streams, then we can map a stream to a sequence of fixed-size files ordered by timestamps. All writes go to the last active file until the file size reaches a specific threshold. Then the last file should be sealed and a new file is created. The idea is very similar to RocksDB WAL.

**Comment by ygf11** [comment]
Hi everyone, I'm also interested in this topic.(@ztelur feel free to take this task).  

IMP, Journal seems is more like a mq than a wal log(pls correct me if i'm wrong), because it  needs random access.
For fast reading events, we need write event index when append, this make implement complicated. 

So I think we can do a simple version first, and add other things after it.
1.   design the base event record format.
2.  reading events without considering index, so reading will search all file.
3.  fixed file size constraint.

**Comment by huachaohuang** [comment]
> IMP, Journal seems is more like a mq than a wal log(pls correct me if i'm wrong), because it needs random access. For fast reading events, we need to write event index when append, this make implement complicated.

Hmm, I think it only needs sequential access starting from a specific timestamp. And I think most reads only need the latest events for recovery or something or synchronization.

> So I think we can do a simple version first, and add other things after it.
> 
> 1. design the base event record format.
> 2. reading events without considering index, so reading will search all file.
> 3. fixed file size constraint.

If we order files by timestamp, we don't need to search all files.

**Comment by huachaohuang** [comment]
I think there are some assumptions that can be generally applied to Journal:

- Write-optimized instead of read-optimized. The read rate should be very low. Think about how RocksDB uses its WAL. Or how a Raft log is used.
- It is periodically truncated, so the overall data size is small. And if we want to support archiving, we can dump history data to external storage, like, the Storage we provide.

**Comment by ygf11** [comment]
> If we order files by timestamp, we don't need to search all files.

@huachaohuang  Thanks. Got it.
We can using timestamp in file name to find the start of give timestamp section.

**Comment by ztelur** [comment]
I think we can store the mapping of timestamp and index in memory for faster read location calculation and restore it when journal unit recover

**Comment by huachaohuang** [comment]
> I think we can store the mapping of timestamp and index in memory for faster read location calculation and restore it when journal unit recover. And we can write in a batch for more write-optimized like raft-engine

Those are all good ideas :)

**Comment by ztelur** [comment]
could we assume that stream events don't exist for too long time.  With the assumption, the stream files don't grow too big and local journal unit doesn't spend too much time to read files and restores index map when it recovers

**Comment by ztelur** [comment]
This is my outline design. And I'm almost halfway done coding. To avoid reworking, I want to know if it's good enough for first version.  

```
# direction structure of local file system journal
- journal-root-dir
 - stream1
  - released_timestamp
  - active.stream
  - 1638183641.stream 
  - 1638183841.stream
 - stream2
  - ....
```

- `create_stream` function creates new stream dir or reads old data in dir for restoring index mapping when dir already exist;
- `delete_stream` function delete stream dir;
- `read_events`  function gets index from mapping in memory, then read data from target file;
- `write_events` function writes into active.stream and create new index mapping entry. it creates new active file when old one's size reach threshold
-  `release_events` function  deletes mapping entry in memory and writes latest released timestamp into  `released_timestamp` file, then deletes all old stream file which earlier than latest released timestamp in async mode

**Comment by huachaohuang** [comment]
@ztelur Your design looks fine to me. But the codebase is facing a massive change recently and I am focusing on designing other things. So I think I need some time to clean things up before coming back to this.

**Comment by ztelur** [comment]
Ok, but how long we can come back to continue this work?

**Comment by huachaohuang** [comment]
@ztelur I think we can come back to this within two weeks.

**Comment by huachaohuang** [comment]
@ztelur Sorry for blocking your work on this. I have cleaned things up in https://github.com/engula/engula/pull/153. Now we can resume the work on this issue. Are you still interested in this job? If you do, we can continue the discussion about your design in https://github.com/engula/engula/issues/128#issuecomment-981555596 :)

**Comment by huachaohuang** [comment]
BTW, we are going to need this for v0.2.

**Comment by ztelur** [comment]
Ok, any suggestion about my design?

**Comment by huachaohuang** [comment]
@ztelur Your design looks good to me. Go ahead and please keep the first implementation simple :)

**Comment by tisonkun** [comment]
@ztelur one concern is that milestone v0.2 will include this issue and we plan to build a file kernel based on file journal also. So there will be a time estimate. You may give an estimate if it takes more than a week to submit a patch. We're open to listening to challenges you encounter if any.

**Comment by ztelur** [comment]
Ok, I will make a pull request roughly next Tuesday.

**Comment by ztelur** [comment]
I need help. `Journal.stream` function returns a clone of stream and  `stream.write` and `stream.read`  maybe is called after that, but file stream has  the `File` and `BufWriter` member variables. How to handle the situation that more than one clone of streams write event ?

**Comment by tisonkun** [comment]
@ztelur you may create a draft PR or send a link to your branch, and we discuss code (implementation) on the patch directly. Sentences in this case express poor than code.

**Comment by ztelur** [comment]
Ok, I will create a draft PR tonight
