### ISSUE TITLE
A file kernel that stores everything in local files

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#147]
A file kernel integrates a file journal, storage, manifest, etc.

**Comment by huachaohuang** [comment]
This can be started after #167

**Comment by ZhongliGao** [comment]
Please assign this task to me and I will give the design as soon as possible

**Comment by tisonkun** [comment]
> Please assign this task to me and I will give the design as soon as possible

@ZhongliGao if so, I think you can just post the ideas without assigned. Being assigned is no more than a hint and your comment here already takes effect.

**Comment by tisonkun** [comment]
@huachaohuang is this issue also blocked by #128?

**Comment by huachaohuang** [comment]
> @huachaohuang is this issue also blocked by #128?

Oh, I think so. But it's ok to prepare for it. The kernel part is not hard, it will be similar to a type alias like the memory kernel. So I think most work here is about the manifest, which needs to persist the metadata in local files.
