### ISSUE TITLE
Add a simple command to do local checks before sending PRs

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#150]
We need to run several commands to check tests, style, license, unused dependencies before sending a PR, which is tedious. Maybe we can add a simple way to check everything at once locally.

**Comment by huachaohuang** [comment]
A Makefile is a possible solution, but maybe there is some Rusty solution too.

**Comment by tisonkun** [comment]
I don't meet this requirement and if you need it, you can start with writing your local script.

Basically, the command is documented in the CONTRIBUTING.md and the details and almost oneliners:

```
cargo build
cargo test --workspace
cargo clippy --workspace --tests --all-features -- -D warnings
cargo fmt --all -- --check
```

while several workflows require pre-install binary:

```
cargo audit
cargo udeps--workspace
# apache/skywalking-eyes
# editorconfig-checker/editorconfig-checker
```

**Comment by tisonkun** [comment]
In most cases I meet, CLion or any proper configure IDE can help you to format code. Audit, udeps, and even licenses violation are rare.

**Comment by tisonkun** [comment]
Also, there is a utility [`nektos/act`](https://github.com/nektos/act) to run GitHub Actions locally, although it will setup a container environment which cost some time, but it's the exact workflow running by GitHub Actions.

**Comment by tisonkun** [comment]
If we really need one, either a make target or cargo customized target (if possible, cc @PsiACE) is OK. But to prevent the command out-of-date, we must update the CI workflows to reflect the exact command logics. Otherwise we'll quickly run into an out of sync situation.

**Comment by PsiACE** [comment]
If it's a mandatory check, maybe try pre-commit or adding githooks. If it is optional, consider using a makefile or a custom cargo command.

> But to prevent the command out-of-date, we must update the CI workflows to reflect the exact command logics.

:+1:

**Comment by huachaohuang** [comment]
How does a custom cargo command work in our use cases?

**Comment by PsiACE** [comment]
> How does a custom cargo command work in our use cases?

add a cargo cmd alias like this

```
[alias]
test-all = "test --workspace"
clippy-all = "clippy --workspace --tests --all-features -- -D warnings"
fmt-check = "fmt --all -- --check"
```

**Comment by huachaohuang** [comment]
@PsiACE Can it combine multiple commands into one? Otherwise, it doesn't seem very helpful, I still need to run multiple commands separately.

**Comment by PsiACE** [comment]
> @PsiACE Can it combine multiple commands into one? Otherwise, it doesn't seem very helpful, I still need to run multiple commands separately.

We can try using cargo-make

**Comment by huachaohuang** [comment]
> We can try using cargo-make

Oh, this looks interesting. Any benefit of using it over simple makefiles?

**Comment by PsiACE** [comment]
> Oh, this looks interesting. Any benefit of using it over simple makefiles?

PTAL, https://github.com/PsiACE/engula/tree/intro-cargo-make , cc @huachaohuang  @tisonkun 

1. cargo setup
2. cargo lint
3. cargo deps-check
4. cargo workflow

**Comment by huachaohuang** [comment]
@PsiACE Thanks for the trial. I think a simple makefile looks better than that, however.

**Comment by PsiACE** [comment]
> @PsiACE Thanks for the trial. I think a simple makefile looks better than that, however.

ok
