### ISSUE TITLE
Port mini-redis to store data in the hash engine

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#160]
From Zulip:

> Hmm, maybe we can let [mini-redis](https://github.com/tokio-rs/mini-redis) run on our hash engine. I think the job should not be hard since `mini-redis` stores everything in a [HashMap](https://github.com/tokio-rs/mini-redis/blob/master/src/db.rs#L64). It will be an interesting way to demonstrate the usage of our hash engine in v0.2.
> We can consider working on that once we get https://github.com/engula/engula/pull/143 landed

This is not required for v0.2. But if anyone is interested in this job, we can add it to the list 🤓

**Comment by ZhongliGao** [comment]
This issue looks interesting, please let me try.

**Comment by huachaohuang** [comment]
@ZhongliGao Hi, do you get anything here for v0.2? If you have a mini-redis on Engula, I can put a link to the project. Otherwise, I will simply close this issue.

**Comment by ZhongliGao** [comment]
> @ZhongliGao Hi, do you get anything here for v0.2? If you have a mini-redis on Engula, I can put a link to the project. Otherwise, I will simply close this issue.

I think you can close this issue for now. mini-redis on Engula link I will post later on the Discussions.
