### ISSUE TITLE
Reduce CI time cost

### ISSUE THREAD

**Issue by DCjanus** [engula/engula#176]
`engula` using some Rust tools, like `cargo-udeps`, `cargo-audit`, maybe we should reduce CI time cost to improve contributor experience.

Mostly, maybe we should download binary rather than runing `cargo install` for every job.

**Comment by tisonkun** [comment]
Thanks for reporting this. A possible solution is https://github.com/engula/engula/issues/110#issuecomment-983272817.

**Comment by huachaohuang** [comment]
Yeah, I also think the Github Action YAMLs contain too many redundant configurations.

**Comment by Xuanwo** [comment]
- `cargo-udeps` provides binary release, Is it OK to download and use it directly?
- How about adding cargo-cache to reduce the build time?

**Comment by PsiACE** [comment]
for cache:

```yaml
    - name: Cache Rust
      uses: Swatinem/rust-cache@v1
```

or

```yaml
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-cache-${{ inputs.cache_reset_key }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-cache-${{ inputs.cache_reset_key }}-
          ${{ runner.os }}-cargo-cache-
          ${{ runner.os }}-cargo-
```

**Comment by huachaohuang** [comment]
Sorry that I didn't review #179 carefully. I wonder why we don't simply use [action/rust-cache](https://github.com/marketplace/actions/rust-cache) instead of handling the cache manually? The [action/rust-cache] looks very simple to me, any reason for not using it? /cc @Xuanwo @PsiACE
