### ISSUE TITLE
elaborate the contributing guide

### ISSUE THREAD

**Issue by tisonkun** [engula/engula#180]
As the project grows, I answer similar questions again and again. Our current CONTRIBUTING.md somehow lacks information and doesn't specialize in our project. Thus, I propose to elaborate the contributing guide a bit to cover the following topics:

* Get started
  * Prepare the development environment
  * Run examples
* Communications (why communications are important, how we organize discussions)
  * Discussion forum
  * Zulip chat room
* Contributions
  * Principles ([reference](https://github.com/tisonkun/engula.github.io/blob/community-project/docs/posts/community-project.md#participation))
  * Report issues
  * Review patches (it should be intuitive but many (potential) contributors ask me about this topic)
  * Contribute code (it should be intuitive also, with satisfying our CI tasks)
  * Licenses (many contributors confuse where a license header should be placed)

I'm going to prepare a PR this week to catch up on the exposure of v0.2 release. The points above are insights. If things go complex (I hope not yet), it can be factored out to the `docs/` folder.

**Reference**:

* [rustc dev guide](https://rustc-dev-guide.rust-lang.org/contributing.html)
* [flink how to contributibute](https://flink.apache.org/contributing/how-to-contribute.html)
* [python dev guide](https://devguide.python.org/)

cc @huachaohuang 

cc @Xuanwo @zojw @DCjanus any information you think there should be?

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/145769182-c3e3d60d-a8fe-42b7-94da-1235d0397ec2.png)

Flink's contributing guide gives many hints on Contribution 😄。

**Comment by tisonkun** [comment]
Hi audiences,

I prepare a pull request #192 to resolve this issue.

I'm trying to elaborate the contributing guide a bit to help on answering repeating questions, while keep short to avoid pulling too much context before we have more contributors.

Guides in references give many hints but they themselves are too complex than what Engula community needs at the moment. I don't just pull long text to describe things overdetailed before I meet a real requirement.

Looking forward to your reviews on #192 :)
