### ISSUE TITLE
Consider following the Cargo.toml conventions

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#181]
There is a Cargo.toml style guide [here](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/cargo.md). We can consider following it.

**Comment by tisonkun** [comment]
As mentioned in #183, I'm curious whether there is a checker for these rules; otherwise, even if we create a patch to follow them, it's easily to be broke later.

**Comment by huachaohuang** [comment]
I surely don't mean to do that mannually 🤣 . I think we can configure Taplo to follow the conventions somehow.

**Comment by ygf11** [comment]
> I surely don't mean to do that mannually.

Sorry for misunderstanding your thoughts.
But I'm not sure Taplo can do all rule check in conventions.

**Comment by tisonkun** [comment]
@ygf11 that's what an assignee of this issue should do. Figure out whether taplo can do it or not, and if it can, submit a patch; if not, discussion for alternatives or close the issue as won't do.

**Comment by ygf11** [comment]
>  that's what an assignee of this issue should do. Figure out whether taplo can do it or not, and if it can, submit a patch; if not, discuss for alternatives or close the issue as won't do.

Ok, It's interesting. let me have a try:)

**Comment by ygf11** [comment]
@huachaohuang @tisonkun I found `taplo` can do some checks, like following:
1. Sorting key-value pairs by key name alphabetically in a section(exception of package section).
2. Put a single space both before and after the = between a key and value.(Taplo default behavior)
3. For array values, expand arrays to multiple line if it exceed the maximum column width(default 80).
4. For array values, collapse arrays that don't exceed the maximum column width.

conventions can not do:
1. Put a blank line between the last key-value pair in a section and the header of the next section.
2. Key-value pairs sorting style in `package` section, which puts name and version in the top level, then other key-value pairs(alphabetical order), and put `description` at the end of that section.
3. When a key-value pair is too long in dependency section , modify it like following:
```
[dependencies]
crate1 = { path = "crate1", version = "1.2.3" }

[dependencies.extremely_long_crate_name_goes_here]
path = "extremely_long_path_name_goes_right_here"
version = "4.5.6"
``` 
4. Other trivial conventions, like `author`, `homepage`,`description` check etc.   

I also found another Cargo.toml formatter, [`dprint`](https://github.com/dprint/dprint).
Other than four rules which `Taplo` supports, it also supports key-value pairs sorting style in package section.
But it has an exception, sorting key-value pairs alphabetically only take affect on dependency section, other sections will not , like `features`.

what do you think?

**Comment by tisonkun** [comment]
@ygf11 sorry to reply late. Last week we're preparing [the release](https://github.com/engula/engula/discussions/206) and this comment was missed from my schedule. I'm looking into it now.

**Comment by huachaohuang** [comment]
Oh, I didn't recall this either. @ygf11 @tisonkun thanks for helping.

**Comment by tisonkun** [comment]
@ygf11 thanks for your investigation. I think you can submit a pull request turn on relative checks in taplo's config file.

For those conventions cannot do, you can try to create an issue in [taplo community](https://github.com/tamasfe/taplo/issues) (e.g., https://github.com/tamasfe/taplo/issues/196) and see if you can cooperate somehow. **This one is a suggestion only, not what you're asked to do.**

**Comment by xxchan** [comment]
After seeing the style guild, I'm wondering whether rustfmt supports it, and I found this has been discussed https://github.com/rust-lang/rustfmt/issues/4091. They will support this, but no progress yet. So I think we can just turn on some taplo check now and use rustfmt solely when it's ready.

**Comment by tisonkun** [comment]
@xxchan sorryfor reply late. As @ygf11 doesn't response, would you mind to submit a pull request to turn on related options?
