### ISSUE TITLE
How to determine whether a stream and bucket is exists in grpc implementation?

### ISSUE THREAD

**Issue by w41ter-l** [engula/engula#194]
When preparing https://github.com/engula/engula/pull/193, I found that both journal and storage grpc client doesn't validate whether there exists a stream or bucket.  Therefore, apart from calling create or performing operations on the stream/bucket, there is no other means to check whether the stream with the corresponding name exists.

Maybe we should add an RPC to verify the existence of the corresponding name?

**Comment by huachaohuang** [comment]
Something like `GetStream`/`ListStream` can be added. But I think it is not necessary for now?

**Comment by huachaohuang** [comment]
This issue is obsoleted by the new design.
