### ISSUE TITLE
Use `Arc<dyn Trait>` instead of `Arc<Box<dyn Trait>>`

### ISSUE THREAD

**Issue by songzhi** [engula/engula#2]
It's [redundant allocation](https://rust-lang.github.io/rust-clippy/master/index.html#redundant_allocation).

Seems you don't use [Clippy](https://github.com/rust-lang/rust-clippy), it's a very useful linter.

**Comment by huachaohuang** [comment]
Wow, that makes sense, thanks. BTW, can you help to add Clippy to the project?

**Comment by songzhi** [comment]
@huachaohuang You can manually call `cargo clippy` or use [rust-analyzer](https://rust-analyzer.github.io/) and with setting `  "rust-analyzer.checkOnSave.command": "clippy",`. Of course it can also be used in CI if there's one.
