### ISSUE TITLE
Make a workable Luna engine

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#221]
## Database

- [x] #294
- [x] #297 
- [x] #299 
- [x] #300
- [x] #302
- [x] #303
- [x] #318
- [x] #319
- [x] #321
- [x] #320
- [x] #308
- [x] #310
- [x] #337
- [x] #338
- [ ] Implement compactions
- [x] #343
- [ ] #346

## Table

- [x] #217
- [x] #255 
- [x] #217
- [x] #255 
- [x] #305
- [x] #313

**Comment by PatrickNicholas** [comment]
@huachaohuang I can try to complete the BlockIter after the iterator is defined. Do you have any plans?

**Comment by huachaohuang** [comment]
@PatrickNicholas I haven't got time to make a more clear plan yet. I implemented a part of iterators in https://github.com/engula/engula/pull/224. If you are interested, you can help to review and test. Then you can try to implement things like BlockIter, TableReader, Filter, compressions, etc.

**Comment by huachaohuang** [comment]
BTW, the demo 1 implementation can be used as a reference.

**Comment by huachaohuang** [comment]
`TableReader` requires an asynchronous random access reader. We need to abstract a set of IO traits instead of those from Tokio. For example, `SequentialRead`, `SequentialWrite`, `RandomRead`, `RandomeRead`.

**Comment by tisonkun** [comment]
@huachaohuang I notice that current luna engine doesn't talk to kernel. What's the role the kernel plays for supporting the luna engine?

**Comment by huachaohuang** [comment]
> @huachaohuang I notice that current luna engine doesn't talk to kernel. What's the role the kernel plays for supporting the luna engine?

It will be similar to the hash engine.

**Comment by tisonkun** [comment]
@huachaohuang could you create issues for all subtasks? As in https://github.com/pingcap/tidb/issues/28170, so that I can try to find contributors for taking every subtask and it's more easy to track the process (for now, BlockReader & TableReader are done but not updated) and to understand what tasks are concretely focused.

**Comment by huachaohuang** [comment]
Closed in favor of #359.
