### ISSUE TITLE
feature request - Support `localhost` in address

### ISSUE THREAD

**Issue by gaocegege** [engula/engula#222]
## Behavior

```
$ engula journal run localhost:8888 --mem
error: Invalid value for '<ADDR>': invalid IP address syntax
```

##  Expected

Just works as `127.0.0.1:8888`

##  Version

6c59de2

**Comment by tisonkun** [comment]
It seems Rust's `SocketAddr` fails to parse "localhost:8888".

```rust
            let mut groups = [0; 4];

            for (i, slot) in groups.iter_mut().enumerate() {
                *slot = p.read_separator('.', i, |p| {
                    // Disallow octal number in IP string.
                    // https://tools.ietf.org/html/rfc6943#section-3.1.1
                    p.read_number(10, Some(3), false)
                })?;
            }

            Some(groups.into())
```

only accept `ddd.ddd.ddd.ddd`. Thus when Clap tries to parse the string into `SocketAddr`, it fails with the message above.

**Comment by gaocegege** [comment]
Yeah, it is hardcoded to only support IP. 

Maybe we should use the struct like [`inetaddress`](https://stackoverflow.com/questions/47263813/what-is-the-difference-between-socketaddress-and-inetaddress-in-java) to support hostname.

**Comment by Xuanwo** [comment]
Take https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html#examples for reference.

**Comment by tisonkun** [comment]
@Xuanwo thanks for investigation! I learn from how we previous tested grpc implement and prepared a patch.
