### ISSUE TITLE
Add test for engula binary

### ISSUE THREAD

**Issue by tisonkun** [engula/engula#226]
This follow up https://github.com/engula/engula/pull/225 can be avoid if we have a test for engula binary.

However, current CI workflows is a bit repeat itself. If I simply add one new, it requires repeatedly installing Cargo toolchain and build the binary again. Thus, I propose to sort out workflows as @Xuanwo's proposal in https://github.com/datafuselabs/databend/discussions/3415.

I'm not working on this now, so feel free to take it over.

**Comment by Xuanwo** [comment]
I will work for it.

**Comment by tisonkun** [comment]
@Xuanwo after some investigation I notice that you should always setup the environment per job. If so, then it seems introducing `needs` doesn't help a lot.

**Comment by tisonkun** [comment]
After notice that we don't need to introduce a "framework" as databend which seems too complex for now, I'm going to integrate the e2e test by myself.

@Xuanwo you can always prepare a pull request or demo and we can review if what you did in databend valuable for our case here. According to the concern above I don't find a good reason to use, though.

**Comment by tisonkun** [comment]
I'm trying to add an e2e test as in [here](https://github.com/engula/engula/runs/4630797465?check_suite_focus=true). However, it seems "localhost" on GitHub Actions Runner cannot be properly parsed. Also, to wait for servers bootstrap in the background is determinately a bit challenging without liveness detection.

Perhaps we will include servers bootstrap in engula operator or docker compose, and then we can add e2e tests with that infrastructure. FYI @zojw @gaocegege.
