### ISSUE TITLE
Roadmap 0.3 - Refactor Journal interfaces

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#229]
```rust
pub trait Journal {
    type StreamReader;
    type StreamWriter;

    async fn create_stream(&self, name: &str) -> Result<()>;
    async fn delete_stream(&self, name: &str) -> Result<()>;
    async fn new_stream_reader(&self, name: &str) -> Result<StreamReader>;
    async fn new_stream_writer(&self, name: &str) -> Result<StreamWriter>;
}
```

Introduce stream reader/writer to separate concerns. Most use cases will not read and write the same stream at the same time. Separating stream reader/writer has another benefit, allowing different compositions of reader and writer.

**Comment by tisonkun** [comment]
> allowing different compositions of reader and writer

If you use associated type, I'm afraid that each instance of `Journal` has fixed composition of reader and writer. For example:

```rust
impl crate::Journal for MemJournal {
    type StreamReader = MemStreamReader;
    type StreamWriter = MemStreamWriter;
    ...
}
```

**Comment by w41ter-l** [comment]
@huachaohuang The `StreamReader` in Journal interfaces in master branch seems that missing the `watch` method?

**Comment by w41ter-l** [comment]
At the same time, the `StreamWriter` interface cannot express the semantics of a leader based journal(which client is responsible for acting as the leader) and provide a mechanism which detecting leader failures .

**Comment by huachaohuang** [comment]
@w41ter-l We need to further refactor the Journal interfaces. Can you foresee what kind of methods do we need in a leader-based journal implementation?

**Comment by w41ter-l** [comment]
@huachaohuang I thought about it for a while, maybe we don't need to add an interface for `StreamWriter`, but block when calling `new_stream_writer` until it win the campaign. And the leader failure detector is hidden in `new_stream_writer`.

**Comment by huachaohuang** [comment]
I am considering some thing like this:

```rust
enum Event {
    Update(...),
    ChangeRole(Role),
}

enum Role {
    Leader,
    Follower,
}

trait Stream {
    type Watcher: Stream<Item = Event>;
    async fn watch(&self) -> Self::Watcher;
}
```

Multiple instances can watch the same stream at the same time. One of them will receive an event `Event::ChangeRole::Leader` and others will receive `Event::ChangeRole::Follower`. If an instance receives the former, it will act as a leader.

**Comment by w41ter-l** [comment]
There are two question about the former proposal. First the `watch` might take a parameter as the cursor, otherwise Journal couldn't find the right position to publish update events. Second `Event::ChangeRole` introduce the complexity to implement, imagine that a user receives a `ChangeRole::Follower` event but invoke `new_stream_writer` immediately, the Journal need to handle those situitions. I think blocking on `new_stream_writer` is enough to handle role changes.

**Comment by huachaohuang** [comment]
@w41ter-l since you are working on the Journal, feel free to prototype the interfaces as you see fit. We can discuss it when we have a more detailed design.

**Comment by huachaohuang** [comment]
We can also further divide the interfaces into two levels. The first level provides some basic interfaces. The second level extends the basic interfaces with leader-based features.

**Comment by huachaohuang** [comment]
We can remove the timestamp from the Journal too. Users can encode their timestamps in the data when necessary. Journal can maintain an increasing sequence number internally and returns the sequence number to users on every write. Then users can use the sequence number to archive or release data from Journal.

**Comment by huachaohuang** [comment]
> We can remove the timestamp from the Journal too. Users can encode their timestamps in the data when necessary. Journal can maintain an increasing sequence number internally and returns the sequence number to users on every write. Then users can use the sequence number to archive or release data from Journal.

I will start refactoring some interfaces for this so that I can continue working on the upper `Kernel` and `Engine`. But I will leave the leader-based semantics to future works.

**Comment by tisonkun** [comment]
@huachaohuang I suggest you guys create subtasks for dedicated work so that a `ref #229` replaced by `ref #xxx` and gather related information. Also, you can even duplicate previous discussion in PR description to help reviewers catch up the motivation and major changes quickly.

Some good cases:

* https://github.com/engula/engula/pull/238
* https://github.com/engula/engula/pull/224
* https://github.com/engula/engula/pull/252
* https://github.com/engula/engula/pull/193

**Comment by huachaohuang** [comment]
@tisonkun Thanks for the suggestions. Makes sense to me.

**Comment by huachaohuang** [comment]
Some of the jobs are done here. For the leader-based API, please open a new issue for it when necessary. Also check #203 for more information.
