### ISSUE TITLE
Remove branch filter on workflow trigger strategy

### ISSUE THREAD

**Issue by tisonkun** [engula/engula#23]
@huachaohuang @ZhongliGao I don't know why you guys change the branch name, but if it's the case and we have only interest branches on the upstream repository (i.e., no personal branch), we can trigger the workflow on every "push" and "pull request" event.

See also https://docs.github.com/en/actions/reference/events-that-trigger-workflows#configuring-workflow-events .

**Comment by huachaohuang** [comment]
There are two reasons:

- We are going to have another demo that may not share the code with the current one. So we need two different branches.
- We will keep these demo branches forever to avoid breaking links to the code. But we don't want to keep them in the main branch.

**Comment by tisonkun** [comment]
Get it. Go ahead!
