### ISSUE TITLE
GitHub Action cache improve

### ISSUE THREAD

**Issue by DCjanus** [engula/engula#230]
There are so many `cargo install xxx` in our GitHub Actions, and I noticed that too many jobs missed the cache, most of them cause by cache key, and maybe we should use correct cache key.

For example: 

+ Jobs which required `cargo install cargo-udeps`, cache key should **not** contain `hashFiles('**/Cargo.lock')`, and `cargo instal` would skip actual install if there is no new version.

+ Jobs which required `cargo build` or `cargo test` or `cargo clippy`, I'm not sure `hashFile('**/Cargo.lock')` should be part of cache key or not. Most commits add or remove some dependencies in `Cargo.toml`, which don't mean we should drop all build cache files.

There is an action called [rust-cache](https://github.com/Swatinem/rust-cache), it compute a cache key from github `job`, rustc release / host / hash, `Cargo.toml`/`Cargo.lock` if present, `rust-toolchain` / `rust-toolchain.toml` if present.

In my case, I think most of our jobs should be look like this:

steps:
    - Install Rust Toolchains
    - Load Cache via `rust-cache` ( cache key without `Cargo.toml`/`Cargo.lock`)
    - Git Checkout
    - `cargo build` Or `cargo instal`

But in such situation, most of jobs share single cache key until next rust stable released, which is really tricky.

**Comment by DCjanus** [comment]
In my view, most of our jobs should use a cache key in those parts (maybe it would be a hash):

- GitHub Job ID
- Output of `cargo --version` which looks like `cargo 1.59.0-nightly (fcef61230 2021-12-17)`
- Output of `rustc --version` which looks like `rustc 1.59.0-nightly (51e8031e1 2021-12-25)`
- Output of `date +"week: %U of %Y"` // To refresh cache every week

**Comment by tisonkun** [comment]
> There are so many cargo install xxx in our GitHub Actions, and I noticed that too many jobs missed the cache, most of them cause by cache key, and maybe we should use correct cache key.

Could you share the related code snippet & actions logs supporting this sentence?

**Comment by DCjanus** [comment]
> Could you share the related code snippet & actions logs supporting this sentence?

For example, now (2021-12-27), there are 13 `Check TOML` workflow, and all of them were cache missed. And cost 3~4 mins each.

URL: https://github.com/engula/engula/actions/workflows/check-toml.yml?query=branch%3Amain
Screen Shot (notice workflow time cost):
![图片](https://user-images.githubusercontent.com/15802727/147414913-b612f4de-f639-483f-8319-078e8fc336d5.png)

**Comment by tisonkun** [comment]
@DCjanus You can take a look at https://github.com/engula/engula/pull/238 and prepare a pull request for this. I think you're in the correct direction. Go ahead!

**Comment by DCjanus** [comment]
The pull request looks good to me, tisonkun is genius.
