### ISSUE TITLE
Release branch names

### ISSUE THREAD

**Issue by tisonkun** [engula/engula#239]
@huachaohuang When working on #238, I just notice that the release branch named `release`. Should it be `release-0.2`? Otherwise, what will happen when we start releasing v0.3?

**Comment by huachaohuang** [comment]
The release branch contains all releases. Versions are represented by the tags on the release branch.

**Comment by tisonkun** [comment]
Well, it seems OK for current requirements. Let's postpone the branch issue when we start doing a backport. At that moment we will need a branch dedicated for a minor version.
