### ISSUE TITLE
Add a crate for common async traits and utilities

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#248]
We will need some common async traits and utilities as the project develops. We can add a crate like `engula-futures` to host the runtime independent things instead of mixing them in `engula-runtime`.

**Comment by tisonkun** [comment]
Looks great! I'd like to ask what we focus on customizing async stuff now? Async IO? Or a general worker/scheduler runtime?

**Comment by huachaohuang** [comment]
> Looks great! I'd like to ask what we focus on customizing async stuff now? Async IO? Or a general worker/scheduler runtime?

Not sure about the priority yet. But I do need some traits at hand right now.
