### ISSUE TITLE
Introduce dependabot

### ISSUE THREAD

**Issue by tisonkun** [engula/engula#258]
[Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates) supports automatically updating Cargo dependencies.

[databend](https://github.com/datafuselabs/databend/blob/main/.github/dependabot.yml) and [tikv/yatp](https://github.com/tikv/yatp/blob/master/.github/dependabot.yml) already makes use of it and I think it's a net win to introduce such bot for Engula so that we don't have to update dependencies manually.

A prerequisite is that @huachaohuang whether you think we should keep all dependencies up-to-date? If so, please mark this issue as good-first-issue so that contributors can deal with the details. If not, close it with explanations.

**Comment by PsiACE** [comment]
https://github.com/datafuselabs/databend/issues/3785

emmm, Dependabot is good, but not enough

**Comment by huachaohuang** [comment]
I don't think this is necessary for now, considering that the current codebase is still very unstable. It seems a nice thing to have in the future, though.

**Comment by huachaohuang** [comment]
Close this for now until we have a more stable codebase.
