### ISSUE TITLE
`futures::io::RandomRead` should not receive a mutable reference

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#261]
I think a positional read doesn't need to change the internal state of a reader. So a mutable reference is not required. Can we use an immutable reference instead?

**Comment by zojw** [comment]
ref #290 maybe RandomRead also no need to support concurrent reads?

It seems `RandomRead` still needs to maintain the state and better be mutable.

The image that we are implementing is above an async gRPC Read method, at first Read method return a Pending future, we need someplace to save it ----- it's naturally to save it in the implemented struct as a field, and find previous future when it's waked up. If not, we need to use a concurrency map in struct and lookup when pending future is waked up for different read requests. 

maybe just like https://github.com/engula/engula/issues/290#issuecomment-1013682073, each caller creating self's RandomRead instance is better~?

**Comment by tisonkun** [comment]
> ref #290 maybe RandomRead also **no** need to support concurrent reads?

@zojw according to #290, do you mean "also need to"?

**Comment by zojw** [comment]
> > ref #290 maybe RandomRead also **no** need to support concurrent reads?
> 
> @zojw according to #290, do you mean "also need to"?

No... I mean **no** need. I propose it should have multiple concurrent RandomRead instances, but no concurrent operations for one RandomRead too (just like https://github.com/engula/engula/issues/290#issuecomment-1013682073, I guess

**Comment by huachaohuang** [comment]
Interesting. One of the most important benefits of "positional read" is to support concurrent read. For example, from the standard library, [`read`](https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read) takes a mutable reference, while [`read_at`](https://doc.rust-lang.org/std/os/unix/fs/trait.FileExt.html#tymethod.read_at) takes an immutable reference.
