### ISSUE TITLE
Support Shared Storage

### ISSUE THREAD

**Issue by zojw** [engula/engula#263]
This is a tracking issue for implementing the cache storage

the design can be found in #247 

- [x] Prototype & Basic Trait #252
- [x] Implement Storage trait for S3 #271
- [x] #322
- [x] #323
- [x] #324
- [x] #332
- [ ] Port-back file system local storage for cache node service
- [ ] Replace mocked orchestrator by k8s backend implement

**Comment by zojw** [comment]
I'd like to take 2nd item: "implement Storage trait for S3" first and investigate 3rd item after finish it

**Comment by huachaohuang** [comment]
Thanks. I had some discussion with @zojw and he would like to take over the design and implementation of the cached storage once #252 gets merged.

**Comment by zojw** [comment]
Hi, I'd update the issue sub-task list with more component implementation details

and I'd like to take 3rd item "Define Communication API between components and implement as Remote Storage Trait" first, it will demonstrate how components work together and final use API (trait)(for implements detail it's planning to use memory or mock implement first in this work item)

**Comment by tisonkun** [comment]
@zojw could you create issues for all these subtasks? The reason as in https://github.com/engula/engula/issues/221#issuecomment-1013798397. Of course, you can always make your progress but describing the status helps participants to extend your strength.

For example, currently the S3 implementation isn't well tested and you can create an issue for it.

**Comment by zojw** [comment]
The shared storage development work has been migrated to another repo as one of engula's external implements, the related issue has be replaced with https://github.com/zojw/shared-storage/issues/4, so close this first
