### ISSUE TITLE
Bring back hash-engine

### ISSUE THREAD

**Issue by tisonkun** [engula/engula#272]
Inspired by https://github.com/engula/engula/issues/221#issuecomment-1008024557 and as https://github.com/engula/engula/pull/269 merged, I'm going to bring back hash-engine.

It's also a blocker for #226.

However, I don't want to act as an assignee, which means you can take it over if it blocks you also. And I think this is a valuable task for anyone who wants to implement their own engine.

**Comment by huachaohuang** [comment]
hash-engine is mainly for demonstration when it is built. There is no long-term plan to maintain it so far. So I don't suggest bringing it back simply to make something work. However, if someone has a plan to turn hash-engine into something more valuable, I am happy to know.

**Comment by tisonkun** [comment]
@huachaohuang a demonstration is enough for contributors understanding how to build an engine. Currently, there's no workable engine which is a user directly talk to.

If you don't think hash-engine valuable and work for connect luna-engine to the kernel, you can remove hash-engine code to reduce confusion.

**Comment by huachaohuang** [comment]
I don't see the necessity to remove the hash-engine either. Just leave it alone until we really decide to drop it.

> For me, it's a cutting point for getting used to Engula's architecture.

If this is the purpose, I suggest that you build an engine outside of the project using the low-level modules. It helps us understand how it is like to build a third-party engine in the current stage :)

**Comment by tisonkun** [comment]
Closed as invalid.
