### ISSUE TITLE
Should we allow concurrent writes to `StreamWriter`

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#290]
The current `StreamWriter` interface accepts a mutable reference, which doesn't allow concurrent writes:

```rust
#[async_trait]
pub trait StreamWriter {
    /// Appends an event, returns the sequence of the event just append.
    async fn append(&mut self, event: Vec<u8>) -> Result<Sequence>;

    /// Truncates events up to a sequence (exclusive).
    async fn truncate(&mut self, sequence: Sequence) -> Result<()>;
}
```

In this case, the user has to do some concurrency control outside. But it seems that the `StreamWriter` has more information to handle concurrent writes internally. So can we allow concurrent writes to `StreamWriter`?

**Comment by tisonkun** [comment]
@huachaohuang could your provide a usage of `StreamWriter` requiring concurrent writes? The discussion would be concrete and focused if we have such an example and thus test case to pass.

**Comment by huachaohuang** [comment]
So luna engine needs to handle concurrent writes from users. With the current `StreamWriter`, there are two ways I can handle concurrent writes:

- Wrap the `StreamWriter` with a `Mutex`
- Use a mpsc channel and send all writes to a single consumer, which writes to the `StreamWriter`

I think it is possible for the `StreamWriter` to handle concurrent writes more efficiently inside. For example, writes to different servers concurrently.

**Comment by w41ter-l** [comment]
@huachaohuang In my assumption, `open_stream_writer` can be called multiple times, each time the `StreamWriter` returned is valid. In the case you mentioned, multiple StreamWriters can be created, and it is up to the implementation to support concurrent calls from different `StreamWrite` instances.

**Comment by huachaohuang** [comment]
This issue is obsoleted by the new design.
