### ISSUE TITLE
`engula` binary not produced when running `cargo build`

### ISSUE THREAD

**Issue by skyzh** [engula/engula#292]
According to the CONTRIBUTING docs:

https://github.com/engula/engula/blob/9211ea72c7d2267c4bba9ae2a1df37ccce64ae4f/CONTRIBUTING.md#L29-L42

But after I run `cargo build`, the engula binary seems not to be built.

I tried adding below config into `Cargo.toml`

```toml
[[bin]]
name = "engula"
path = "bin/engula.rs"
```

But there seems to be compile error:

```
   Compiling engula v0.3.0 (/Users/skyzh/Work/engula)
error[E0432]: unresolved imports `engula_journal::file`, `engula_journal::grpc`, `engula_journal::mem`
  --> bin/engula.rs:19:5
   |
19 |     file::Journal as FileJournal, grpc::Server as JournalServer, mem::Journal as MemJournal,
   |     ^^^^                          ^^^^                           ^^^ could not find `mem` in `engula_journal`
   |     |                             |
   |     |                             could not find `grpc` in `engula_journal`
   |     could not find `file` in `engula_journal`
```

Is this binary executable `engula.rs` still maintained? Thanks!

**Comment by tisonkun** [comment]
@skyzh I think the binary was opt-out in https://github.com/engula/engula/pull/232 during the refactoring, while CONTRIBUTING.md content isn't updated.

However, during the past weeks we don't finish the refactoring or have a workable software, and I think it's undoubtedly an issue now. If we don't have a workable software, we cannot play with it, verify ideas, or understand how the RFCs improve such a software.

@huachaohuang do you have a plan what we're going to deliver for users and when it will be delivered?

**Comment by huachaohuang** [comment]
The binary is mostly for starting gRPC services. But the existing gRPC services are all broken for now. I suggest that we make a workable engine with the memory implementation first before fixing the gRPC service. A workable engine should be available in these two weeks. But the binary may come a bit later since we are facing the upcoming holidays.

**Comment by huachaohuang** [comment]
#374 introduced a new usable binary. I think this issue can be considered fixed or obsoleted.
