### ISSUE TITLE
Remove gRPC implementation of storage and journal

### ISSUE THREAD

**Issue by tisonkun** [engula/engula#352]
BTW, for share storage and share journal implementation, as previous discussion about separate modules, I propose those implementation leaves in a separated crates and rely on the basic implementation provided by `engula-storage` or `engula-journal`.

Also, current code structure can be refactor a bit so that the root `Cargo.toml` only contains `workspace` section and we move the `engula` crate as `src/engula`. In this way, all crates under this repository are peers, one is not surprised by that one crate has a special layout. This is a code structure refactor thought, anything about publishing won't be affected.

**Comment by tisonkun** [comment]
cc @zojw @w41ter-l @huachaohuang

**Comment by huachaohuang** [comment]
@tisonkun sounds good to me, you can try to do the refactoring.

**Comment by huachaohuang** [comment]
Maybe simple use:

```
engula/  <---- project root
    engula/
    engula-journal/
    ...
```

instead of:

```
engula/src/
    engula/
    engula-journal
```

I'm not sure which one if better 🤔

**Comment by tisonkun** [comment]
@huachaohuang I ever thought of eliminate the `src/` folder. Actually, either style has real-world example.

Flatten to root:
* [tokio-rs/tokio](https://github.com/tokio-rs/tokio)
* [TimelyDataflow/timely-dataflow](https://github.com/TimelyDataflow/timely-dataflow)

Shaded by `src`:
* [rust-lang/rust](https://github.com/rust-lang/rust)
* [MaterializeInc/materialize](https://github.com/MaterializeInc/materialize)

I think the difference is that, if the repository continuously grows and the root path has more staff beyond code, gathering code staff under a folder keeps the root cleaner. In the other hand, even in the examples above "shaded by `src`", they actually separate different crates under different top level folder (rust: `src` vs `library` vs `compiler`, materialize: `src` vs `test` vs `fuzz`).

Thus, the conclusion is that it depends on the repository status. For Engula, I assume that this main repo will grow more and more complex. So I tend to keep all source code under `engula/src` for now, and keep an eye on what evolves.

**Comment by huachaohuang** [comment]
@tisonkun sounds good to me.
