### ISSUE TITLE
The Stream Engine 0.3

### ISSUE THREAD

**Issue by w41ter-l** [engula/engula#426]
# Overview

This is tracking issue for designing and implementing the stream engine in 0.3.

The previous designing and developing work of the stream engine is: https://github.com/w41ter-l/shared-journal/issues/1.

# Tasks

## Documentation
-  [x]  #427 

## Migration shared journal
- [x] #434 
- [x] #435 
- [x] #436 
- [x] #437
- [x] #460
- [x] #461 
- [x] #462 
- [x] #468 
- [x] #479

**Comment by huachaohuang** [comment]
@w41ter-l I am trying to add a basic master service implementation. Then you can take over the rest. How do you think?

**Comment by w41ter-l** [comment]
> @w41ter-l I am trying to add a basic master service implementation. Then you can take over the rest. How do you think?

No problem.

**Comment by huachaohuang** [comment]
Reminder: for anything you want to ship in release 0.3, please submit them before Feb, 27. Or you can simply move them to 0.4.

**Comment by w41ter-l** [comment]
@huachaohuang The replication algorithm and worker still need verificvation, I want to move it to 0.4.

**Comment by huachaohuang** [comment]
@w41ter-l OK, please close this when you are done with 0.3.

**Comment by w41ter-l** [comment]
The sub tasks #480, #481 and the rest are to move to 0.4, close this issue since all tasks list in above are finished.
