### ISSUE TITLE
Introduce logging support

### ISSUE THREAD

**Issue by tisonkun** [engula/engula#466]
So far, when we start engula service, it prints nothing due to we don't add any logging supports.

For interacting with users on healthy and problematic state, I suggest we introduce basic logging support before v0.3 release.

Questions to be answers include:

1. What logging library to use? I prefer [`tracing`](https://crates.io/crates/tracing), but [`slog`](https://crates.io/crates/slog) can be an alternative.
2. What should be logged? The original requirement is I'd like to prompt users that the server has been ready to response. However, you can follow this question and use cases may change the choice we make on logging library.

cc @huachaohuang @breeswish

**Comment by w41ter-l** [comment]
How about the [log](https://crates.io/crates/log) crate?

**Comment by w41ter-l** [comment]
Regarding when and what should be logged, we could start from the perspective of troubleshooting:
1. Critical status changes
2. First time an error occuried
3. The user/other components input is not as expected

**Comment by tisonkun** [comment]
@w41ter-l `log` crate contains thin API definitions and we should choose an implementation. Also `log` doesn't support structure logging stably, I tend to use a de-facto solution then a semi-manufactures even it's provided by rust-lang.

> * `tracing` used widely in tokio ecosystem.
> * `slog` used in tikv for a long time.

BTW, the crates proposed above can bridge to `log` for API compatibility.

**Comment by breeswish** [comment]
There is tokio-metrics and tokio-tracing. I recommend to give them a try.

**Comment by skyzh** [comment]
I would recommend tokio-tracing for both tracing and logging. For metrics, rust-prometheus may help a lot.

**Comment by huachaohuang** [comment]
We can start with tokio-tracing. It is very active and has a good ecosystem. Log whatever you think it's necessary for now. These things will be changed frequently in early development. We can make some rules when integrating with other ecosystems in the future.

**Comment by PsiACE** [comment]
tracing should be the first choice, with rich support and an increasingly robust ecosystem, while also experiencing experimental tools including tokio-console and tokio-metrics.

**Comment by tisonkun** [comment]
I write a small PR for introducing the deps and setups #471. You may give it a review.
