### ISSUE TITLE
Update the release guide after release 0.3

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#487]

**Comment by tisonkun** [comment]
One of the notable information is what crates we want to publish.

A fundamental question of releasing is what to release. I think it currently includes:

1. The source code.
2. Public crates on crates.io. `engula-client`, `engula-api`, ...
3. Convenient binaries to run services.

**Comment by huachaohuang** [comment]
There are only three public crates now: engula, engula-apis, and engula-client. The `engula` crate provides the binary to run services. So we simply need to publish those three crates for now.
