### ISSUE TITLE
Settle down the project layout

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#59]
Rust crates:

- `engula`: the integral library and binary
  - `engula-engine`: contains different kinds of storage engines
  - `engula-kernel`: contains the kernel abstraction and some built-in implementations
  - `engula-journal`: contains the journal abstraction and some built-in implementations
  - `engula-storage`: contains the storage abstraction and some build-in implementations

TODO:

- [ ] Improve descriptions in `Cargo.toml`
  - [x] engula
  - [ ] engula-engine
  - [x] engula-kernel
  - [x] engula-journal
  - [x] engula-storage

**Comment by huachaohuang** [comment]
We have some discussions about the project layout in https://github.com/engula/engula/pull/64#issuecomment-960431302 and https://github.com/engula/engula/pull/64#issuecomment-960433236.

Let me elaborate on the alternative here. We can keep only one top-level crate `engula` and publish it to crates.io. `engula` can contain a lot of internal crates and expose some of them for users. Internal crates are not published so their names can be arbitrary. So the project layout looks like this:

```
engula
   src/
    lib.rs
    api/
      map/
    kernel/
      storage/
    platform/
      object-storage
    microunit/
    ...
```

**Comment by tisonkun** [comment]
@huachaohuang generally I like this layout's looking. For the modularity topic, I'm still investigating "features" mechanism. It seems a conditional compilation approach. I'm unsure whether conditional compilation can handle multiple "modules".

**Comment by huachaohuang** [comment]
Did some experiments about sub-crates. Turns out that it is not going to work if we only publish the top-level crate without the internal crates.

Let's say we have a crate `A` with an internal crate `B`. We can publish only crate `A` without crate `B`. But users of crate `A` will not be able to compile since crate `B` is missing.

So we have two choices: merge everything into one crate or publish all crates at once. I currently prefer the latter. If so, we need to update internal crates, give them a unique name (for example, "journal" will be "engula-journal"), etc.

**Comment by huachaohuang** [comment]
Check [deno dependencies](https://crates.io/crates/deno/1.16.3/dependencies) for an example.

**Comment by tisonkun** [comment]
I'd like to clarify the approaches we can choose:

1. "merge everything into one crate" means like tokio, we publish everything under crate "engula", and users can choose features with feature flags.
2. "publish all crates at once" means like deno, we publish every crate separately, and users can choose crates with their names.

If so, I also prefer option 2 since feature flags may cause casual results in use. Simultaneously publishing is normal for coupled crates and already a mature practice for Maven projects to publish multiple sub modules.

**Comment by huachaohuang** [comment]
Let's close this with #143 and figure out how to release crates in #144 .
