### ISSUE TITLE
Roadmap v0.2 - Journal

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#65]
Tasks:

- [x] Design document
- [x] Journal abstraction
- [x] A memory implementation
- [x] #128 
- [x] #117

**Comment by Little-Wallace** [comment]
How we create a journal stream with other params?  If one tablet is ready to split to two tablet, it means that we shall create one new journal for  the new tablet.

**Comment by huachaohuang** [comment]
> How we create a journal stream with other params?

We can allow users to create a stream with some metadata and persist the metadata in `Journal`. Users may also consider storing metadata in `Kernel`. `Kernel` only supports one stream for now, but we will allow users to create multiple streams sooner or later.
