### ISSUE TITLE
server: decide whether to use mio or uio automatically

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#658]
### Search before asking

- [X] I had searched in the [issues](https://github.com/engula/engula/issues) and found no similar issues.

### Motivation

Automatically choose the best io driver for users according to their platform.

### Solution

Engula supports two io drivers: mio and uio (io-uring).
We can decide whether to use mio or uio with conditional compilation and feature probe.

With conditional compilation:

- If the target os is linux, compile with both mio and uio.
  - On restart
    - if some key feature of io-uring is supported, which makes io-uring performs better, we use the uio driver
    - otherwise, use the mio driver
- Otherwise, compile with mio only

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Thanks for creating this issue @huachaohuang! Here are my two coins:

1. Even when we support auto detection, it's useful to keep the config to force the driver in use.
2. I'm unsure if we always build with uio on `target_os = "linux"`, and run the program on linux with ancient kernel version, will it crash? Also how can we detect whether io-uring is supported at runtime?

**Comment by huachaohuang** [comment]
io-uring consists of a few syscalls introduced at 5.1 (listed [here](https://man7.org/linux/man-pages/man2/syscalls.2.html)). If we call those syscalls on an older kernel, it will return an errno `ENOSYS`. So we try to call the io-uring syscalls first. If it returns a specific error, we simply go to the mio path. Otherwise, the kernel at least supports some basic io-uring features. Then we can probe the feature we need with https://docs.rs/io-uring/latest/io_uring/struct.Parameters.html to decide if we can really go to the uio path. I don't know what features we should test so far, though. Maybe some performance tests are needed to make that decision.
