### ISSUE TITLE
Should we add a crate to manage client related code?

### ISSUE THREAD

**Issue by w41ter** [engula/engula#694]
The current crates designs does not reflect the works done by client. In fact, the code logic of client is very complex, including location cache, routing, error retries, txn ... At the same time, the client code itself will be depended on by other developers.

Therefore I think it is necessary to manage the client as a seperate crate. What is your opinion? @huachaohuang @zojw @tisonkun

**Comment by tisonkun** [comment]
Agree. Basically a separated crates layout should be:

* `client`
* `proto`
* `server`

And both client and server depend on shared protos. Thus developers who want to program with client only don't pollute server code.

**Comment by huachaohuang** [comment]
Yeah, [this PR](https://github.com/engula/engula/pull/693) already included a client crate.
