### ISSUE TITLE
Implement an LRU cache

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#7]
A `Cache` trait has been added with no concrete implementation yet.
We can add a simple LRU cache like RocksDB.
For example, an `LRUCache` can be partition into multiple `LRUShard`, each of which can be a simple `HashMap` protected by a `RwLock`.

Reference: https://github.com/facebook/rocksdb/blob/main/cache/lru_cache.h

**Comment by huachaohuang** [comment]
@PsiACE would you like to take this issue?

**Comment by huachaohuang** [comment]
@PsiACE Hi, how are you doing recently? I am going to do some performance evaluations. It would be nice to have this cache integrated. Do you think you can get it done this week? Let me know if you're too busy for this :)

**Comment by PsiACE** [comment]
I'm sorry, I've been busy with other work lately and I don't have enough energy at the moment.

I will return when I am free.

**Comment by huachaohuang** [comment]
Never mind, you are always welcomed.

**Comment by huachaohuang** [comment]
Closed by https://github.com/engula/engula/commit/112c8a68708e6b2fceecd903aabdbe734d94a96d
