### ISSUE TITLE
Roadmap v0.2 - Engine

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#73]
Provide a simple hash engine that supports `get/set/delete` key-value pairs.
The engine should be able to use different kinds of kernels.

- [x] #168

**Comment by tisonkun** [comment]
@huachaohuang `api/datatypes` already brings `HashMap` `Int64` & `List` API. What's remaining for this issue?

**Comment by huachaohuang** [comment]
@tisonkun #74 only added some basic types to demonstrate the concepts. We still need to provide a proper API to users that actually do something.
