### ISSUE TITLE
completion and elimination the replicas of a group automatically

### ISSUE THREAD

**Issue by w41ter** [engula/engula#762]
Because the leader of the group knows the most about the situation of the group, we hope that the group leader will solve the urgent problems of the group (as long as the group can solve it independently).

Now, if a group leader finds that a replica is missing, it can add a replica on its own to replace the lost replica. To get there, there are several issues that need to be addressed:
1. node liveness: how to detect and judge replica loss
2. The new replica needs to be assigned node and replica id.
3. How to cooperate with load balancing (the current design idea of load balancing is done by root)
4. How to maintain the number of group replicas, and how does the group leader obtain this number?

The raft group periodically sends heartbeats to each replica, so this can also be used to detect if a replica is still responding. If a replica does not respond for more than a period of time, it can be considered lost and question 1 is solved.

For question 2, maybe root is needed to provide an interface to assign node and replica ids?

For question 4, consider configuring the required number of replicas for each database and group. The shards of a database collection can only be migrated between groups with the same number of replicas. And this number, can be saved as a field in `GroupDesc` and `DatabaseDesc`.

**Comment by w41ter** [comment]
Do you have any comments and suggestions on these issues? @zojw  @tisonkun  @huachaohuang

**Comment by huachaohuang** [comment]
For questions 2 and 3, when you ask the root for a new replica id, the root can also suggest the best node to place the replica according to its load balance strategies.
