### ISSUE TITLE
Retry request if client meets errors

### ISSUE THREAD

**Issue by tisonkun** [engula/engula#787]
Refer to https://github.com/engula/engula/pull/781#discussion_r903699925.

If EngulaClient's requests fail for metadata outdated, we may find a way to retry.

However, currently our router state is built only if receive watch events, while HBase client would active request latest metadata (router state). @zojw do you have more input in this issue? Otherwise we can do no more than barely retry several times and hope that the state updated.

**Comment by w41ter** [comment]
> Otherwise we can do no more than barely retry several times and hope that the state updated.

I think the router can add a watch function, when each request needs to be retried, call the watch and wait for the timeout or the expected metadata update.

**Comment by tisonkun** [comment]
@w41ter It seems we should add a timeout mechanism first 😆 

I like your proposal but the issue is that if we wait for retrying current request, shall we proceed other incoming requests? Basically a client should hold a property that every request is handled sequentially.

**Comment by w41ter** [comment]
@tisonkun The assumption of this approach is that the client does not need to guarantee that requests are handled sequentially. 😆

Is there any case that the client needs to handle requests sequentially? My previous understanding is that most systems do not require client guarantees the request order (if there is an ordering requirement, a mechanism like gRPC's stream will be used).

**Comment by zojw** [comment]
> @tisonkun The assumption of this approach is that the client does not need to guarantee that requests are handled sequentially. 😆
> 
> Is there any case that the client needs to handle requests sequentially? My previous understanding is that most systems do not require client guarantees the request order (if there is an ordering requirement, a mechanism like gRPC's stream will be used).

I think tison's questions: req1 meet epochNotMatch, at the same time req2 for same group should aware the failure of req1 and wait  epoch catch up the server

**Comment by tisonkun** [comment]
@w41ter that sounds reasonable. If a user depends on sequential guarantee, they can write code like:

```rust
let v = co.get(k).await?; // (1)
co.put(k f(v))await?; // (2)
```

... which (2) is always executed after (1) returned (transparent retries).

The `put` method can be:

```rust
pub async fn put(k, v) -> ... {
    while let res = put_inner(k, v) {
        if need_retry(res) {
            // register watcher in router and await
         } else {
           return ...;
         }
    }
}
```

**Comment by tisonkun** [comment]
> does req2 should aware the failure of req1 and wait epoch catch up the server?

No. It's over "smart". We should keep independent requests independently.
