### ISSUE TITLE
Implement a BloomFilter

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#8]
A `Filter` trait has been added without an implementation.
We can add a `BloomFilter` like LevelDB.

Reference: https://github.com/google/leveldb/blob/master/util/bloom.cc

**Comment by PsiACE** [comment]
emmm, perhaps try some new filters, such as the xor filter?

**Comment by huachaohuang** [comment]
@PsiACE sounds interesting, how about you take this issue and leave #7 to @ZhongliGao instead?

**Comment by huachaohuang** [comment]
FYI, RocksDB also has a `RibbonFilter`, although it may be too complicated for this demo.

**Comment by PsiACE** [comment]
I thought we could finish a Bloom filter first and then look at other new things. Please let @ZhongliGao continue with this issue.

**Comment by huachaohuang** [comment]
Sure, our long-term vision is to make most components pluggable so that people can explore different kinds of implementations. But for the current demo stage, a simple implementation is sufficient.
