### ISSUE TITLE
Consider separate executable and library

### ISSUE THREAD

**Issue by tisonkun** [engula/engula#89]
In https://github.com/engula/engula/pull/78 we simplify the project layout into:

```
├── Cargo.lock
├── Cargo.toml
├── src
│   ├── api
│   ├── background
│   ├── hello_unit.rs
│   ├── main.rs
│   ├── manifest
│   ├── microunit
│   ├── node.rs
│   └── storage
```

However, the root cargo config file define both the executable and library, while a consumer of the library doesn't want the executable part. We may consider releasing executable and library separately. @zojw suggested learn from how tokio does release.

cc @huachaohuang @PsiACE

**Comment by PsiACE** [comment]
we can move `main.rs` to `bin/` dir, keep a `lib.rs` in `src/` dir

**Comment by huachaohuang** [comment]
Yeah, I have a plan to move `main.rs` to `bin/`, just haven't done that. You can leave this to me :)

**Comment by tisonkun** [comment]
@huachaohuang may we add it in the v0.2 milestone.
