### ISSUE TITLE
offline node doesn't judge as offline after new elected root leader

### ISSUE THREAD

**Issue by zojw** [engula/engula#905]
After the root leader node is shut down, another node can be elected as the new root leader.

It will rebuild memory liveness after a heartbeat tick, but the old root node cannot be accessible but doesn't set entry in memory map, so it will be judged as online node in liveness and we can observe allocator still try transfer replica into offline node

**Comment by w41ter** [comment]
> judged as online node in liveness and we can observe allocator still try transfer replica into offline node

Yes, all memory states should be dropped once the leadership is transfered.
