### ISSUE TITLE
Find a practice to return asynchronous paged results

### ISSUE THREAD

**Issue by huachaohuang** [engula/engula#91]
We have some APIs that need to return a list of values. For example, get a list of object names from a bucket. The simplest way is to return a `Vec<T>`. But if the list goes too long, it is not a good idea to return it all at once. A common solution for this kind of problem is paging. Rust provides a concept called `Stream`, which is like an asynchronous iterator that allows the caller to get one value at a time.

I think the most mature way to do that is to use [Stream](https://docs.rs/futures/0.3.17/futures/stream/trait.Stream.html) from the `futures` crate. But it is not a good idea for our public APIs to depend on a third-party trait, which is not stable either. Fortunately, Rust is working on a built-in [`Stream`](https://doc.rust-lang.org/std/stream/trait.Stream.html) trait (nightly), so we may consider using that in our public APIs when it is stablized.

**Comment by huachaohuang** [comment]
[This post](http://xion.io/post/code/rust-unfold-pagination.html) looks interesting. I haven't checked the details, though.

**Comment by zojw** [comment]
today, I learned sth from https://blog.yoshuawuyts.com/rust-streams/ and other repo..

>  AsyncRead is a byte stream that operates on borrowed data. While Stream is an object stream that operates on owned data

do we need change write/read method in `Object` trait to using & return `AsyncRead`, `AsyncWrite`, because they are byte stream~?

**Comment by huachaohuang** [comment]
> do we need change write/read method in `Object` trait to using & return `AsyncRead`, `AsyncWrite`, because they are byte stream~?

`AsyncRead` is for sequential read while `Object` should support both sequential and random read. So I think may we can make `Object` implement `AsyncRead` somehow.
I actually considered returning a `Box<dyn AsyncWrite>` for `upload_object()` before. But I changed my mind because the purpose of `flush()` in `AsyncWrite` may not be clear when uploading objects, and we may need to add other methods in the future.
That's said, I think we still have a lot of work to do with the APIs. Let's keep building things to get more context about it.
