### ISSUE TITLE
How to generate .rs file from proto file

### ISSUE THREAD

**Issue by flike** [engula/engula#962]
When I Read code in Idea, the RaftMessage Struct not defined in rs file. I want generate rs file from proto file, What should I do ?

**Comment by w41ter** [comment]
The rs file for the proto file is automatically generated when you execute `crate build`, then you can then locate these files in the `target`. 

```
$ ls ./target/debug/build/engula-server-*/out
./target/debug/build/engula-server-01b25d17ba589b0a/out:
engula.server.v1.rs  eraftpb.rs  serverpb.v1.rs

./target/debug/build/engula-server-3242c4b97cf9a903/out:
engula.server.v1.rs  eraftpb.rs  serverpb.v1.rs

./target/debug/build/engula-server-7e01990f4480aea9/out:
```

`RaftMessage` is defined in `serverpb.v1.rs`.

**Comment by flike** [comment]
In this case, Clion editor can't support code jumping. How can you handle this situation when developing code? Why don't you just leave the generated RS file in the corresponding directory?
