### ISSUE TITLE
client root info could not update when epoch=0

### ISSUE THREAD

**Issue by zojw** [engula/engula#972]
Now, our client inits root info with `Arc::default()`, so initial epoch value is `0`.

So root_client couldn't refresh the initial root info from root_server because root_server's epoch is also 0.

This will cause 2nd node join the cluster is very very slow (because root_client still uses fake & empty default RootDesc until RootServer epoch changes for some reason.

**Comment by w41ter** [comment]
> So root_client couldn't refresh the initial root info from root_server because root_server's epoch is also 0.

It seems that the root cause is root server's epoch is 0, but the root server epoch cannot be 0 (by designed).
